### ISSUE TITLE
Dynamic init.yml keys

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#158]
```yaml
archive: manycases.zip

# 1 point per case
points: 1

# 100 testcases will be generated
testcase_count: 100

# Dynamic Keys
# If a node ends with '+' it will be treated as Python code and executed
# to generate the node (without the +). If a node by the name already exists,
# its value will be placed in global scope for the execution of the Python
# generator, and then replaced with the generated value.
#
# The dynamic key below generates 100 cases in the format case.#.(in|out)
# The global node object has access to all parent node values. In this case,
# we make use of the top-level testcase_count node.
test_cases+: |
  print node.testcase_count
  node = [{'in': node['in'] % _, 'out': node.out % _} for _ in range(1, node.testcase_count + 1)]

# This is the template for each testcase
test_cases:
 in: case.%d.in
 out: case.%d.out
```
