### ISSUE TITLE
Testcase format specifiers

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#262]
We need an efficient way to specify testcases in a common format for a contest, where dynamic keys are not an optimal solution. For example, the regex `\w+\.(?<batch>[0-9]+)-(?<case>[0-9]+)\.in` matches most, if not all, COCI data.

That's a lot of data.

That's a lot of lines of `init.yml` saved.

There are probably more broad ways to approach this, but for the general case a simple regex would save a lot of work, even if it loses flexibility for more complex cases (dynamic keys are there for those!)

The following should be valid, after this ticket:

```yml
test_format_in: \w+\.(?<batch>[0-9]+)-(?<case>[0-9]+)\.in
test_format_out: \w+\.(?<batch>[0-9]+)-(?<case>[0-9]+)\.out
point_values: [10, 10, 20, 60]
```

Someday this may be generalized to support setting a format specifier for a specific `test_cases` node, but that is beyond the scope of this ticket. For this ticket, if `test_format_(in|out)` exists, then the `test_cases` node should be ignored.
