### ISSUE TITLE
CI test script spitting out !!python/unicode on Python 2

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#350]
```yaml
 scala_args:
  - !!python/unicode '-Xbootclasspath/a:/usr/share/scala/lib/akka-actor_2.11-2.3.10.jar:/usr/share/scala/lib/config-1.2.1.jar:/usr/share/scala/lib/jline-2.12.1.jar:/usr/share/scala/lib/scala-actors-2.11.0.jar:/usr/share/scala/lib/scala-actors-migration_2.11-1.1.0.jar:/usr/share/scala/lib/scala-compiler.jar:/usr/share/scala/lib/scala-continuations-library_2.11-1.0.2.jar:/usr/share/scala/lib/scala-continuations-plugin_2.11.8-1.0.2.jar:/usr/share/scala/lib/scala-library.jar:/usr/share/scala/lib/scalap-2.11.8.jar:/usr/share/scala/lib/scala-parser-combinators_2.11-1.0.4.jar:/usr/share/scala/lib/scala-reflect.jar:/usr/share/scala/lib/scala-swing_2.11-1.0.2.jar:/usr/share/scala/lib/scala-xml_2.11-1.0.4.jar'
  - !!python/unicode '-classpath'
  - !!python/unicode '''""'''
  - !!python/unicode '-Dscala.home=/usr/share/scala'
  - !!python/unicode '-Dscala.usejavacp=true'
  - !!python/unicode '-Denv.emacs='
  - !!python/unicode 'scala.tools.nsc.MainGenericRunner'
  scala_vm: !!python/unicode '/usr/lib/jvm/java-8-oracle/bin/java'
```
