### ISSUE TITLE
Problem configuration templates

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#363]
It's often the case that some classes of problems repeat the same input format across all problems. For example, all ECOO problems require the same `fd_redirects` declaration, and all have exactly the same test-case format. It would be good to add support for "extending" problem YAMLs off some base configuration.

The proposed approach is the addition of an `extend` key in a problem YAML, that denotes an extension of a user-defined template.

`problem.yml`:

```yaml
extend: ecoo
...
```

`judge.yml`:

```yaml
id: ...
key: ...
problem_template_directory: /code/problem-templates
...
```

`/code/problem-templates/ecoo.(yml|yaml)`:

```yaml
fd_redirects:
    - 0: ...
...
