### ISSUE TITLE
Problem resource linking support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#364]
## Motivation
It is currently very hard to manage the addition problems that need access to different resources than standard problems. An example of a problem that is difficult to support as-is is any that requires the presence of certain libraries that would trivialize other problems on the judge (e.g. `scipy`, `numpy`).

## Proposed Solution
A simple solution for this would be to allow the automatic symlinking of some problem YAML-defined files or directories into each submission's temporary directory. Read rights would be inherited, while writes would continue to be disallowed.

This plays particularly well with #363; it is easy to imagine a `datasci` template that provides symlinks to `numpy` and `scipy`.

## Proposed Configuration
In `init.yml`:

```yaml
symlinks: {
    numpy: /code/runtimes/python/numpy,
    scipy: /code/runtimes/python/scipy
}
```

## Supersedes `fd_redirects`
After this feature is implemented, the current `fd_redirects` can be much more intuitively implemented using symlinks.

```yaml
symlinks: {
    DATA1.in: /dev/stdin,
    DATA1.out: /dev/stdout
}
```

Where multiple cases are present and symlinking manually becomes a pain, dynamic keys can easily be used.
