### ISSUE TITLE
init.json improvements

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#83]
```yaml
archive: game1.zip,
unbuffered: true,
test_cases: [
    {
        in: game1.1.in,
        # interactor instead of grader - what kind of a name is that?
        interactor: game1.py,
        points: 10
    },
    {
        generator: {
            # generator source file
            source: inputgen.cpp,
            # compiler flags
            flags: [-O3],
            # args to pass to executable
            argv: [0, 1, 2, 3]
        },
        interactor: game1.py,
        points: 10
    }
]
```

```yaml
archive: cases.zip,
test_cases: [
    {
        in: case.1.in,
        # This should be optional, defaulting to empty string if checker is specified but out isn't
        # out: null.out,
        # Checker can be specified globally and per-case
        checker: phantomc1.py,
        points: 10
    }
]
```

```yaml
archive: ruby.zip,
output_prefix_length: 500,
test_cases: [
    {
        # rename data to batched: easier to remember
        batched: [
            {
                in: ruby.1.in,
                out: ruby.1.out
            },
            {
                in: ruby.2.in,
                out: ruby.2.out
            },
            {
                in: ruby.3.in,
                out: ruby.3.out
            }
        ],
        # make local output_prefix_length override global
        output_prefix_length: 2500,
        points: 10
    }
]
```

**Comment by FatalEagle** [comment]
While you're at it, allow a global
```
in_format: "game.%1.in"
```
Increments counter automatically.

**Comment by Xyene** [comment]
Notes:

* if `generator` is specified `in` may not be, and vice versa.
* if `checker` is specified, `out` is optional. If `out` is specified, it will be passed to the checker, otherwise the checker will receive an empty string.
* If `interactor` is specified, `out` is optional. See point above.

**Comment by Xyene** [comment]
@FatalEagle we can check if `data['test_cases']` is a `dict`, and if so:

```yaml
test_cases: {
    in_format: "case.%1.in",
    out_format: "case.%1.out", 
}
```

This works well with global `output_prefix_length` and `checker`.

**Comment by Xyene** [comment]
Ties in with #13.

**Comment by FatalEagle** [comment]
@Xyene How would that work when mixed with generators though?

**Comment by Xyene** [comment]
@FatalEagle It wouldn't. At all.

**Comment by Xyene** [comment]
Alright, so local `output_prefix_length` works, and so does the new generator syntax. Local generators are not yet supported, since at worst they require recompilation of the same generator, and I can't think of a solution for this. **Perhaps we should cache all generator binaries, encoded with hash of flags list, until shutdown?** @quantum5

**Comment by Xyene** [comment]
With #111 closed, YAML is now supported for the init files.

**Comment by Xyene** [comment]
We should have a `ConfigNode` object which checks its parents for an attribute if it itself does not contain it. This would allow for nice things like:

```yaml
test_cases: [
    {
        batched: [
            {
                in: ruby.1.in
            },
            {
                in: ruby.2.in
            },
            {
                in: ruby.3.in
            }
        ],
        out: ruby.out,
        points: 10
    }
]
```

The `out` node would apply to every node in the batched group, for example. This would work particularly well with things like `output_prefix_length`.

**Comment by Xyene** [comment]
A note on the first example:

```yaml
archive: game1.zip,
unbuffered: true,
test_cases: [
    {
        in: game1.1.in,
        # interactor instead of grader - what kind of a name is that?
        interactor: game1.py,
        points: 10
    },
    {
        generator: {
            # generator source file
            source: inputgen.cpp,
            # compiler flags
            flags: [-O3],
            # args to pass to executable
            argv: [0, 1, 2, 3]
        },
        interactor: game1.py,
        points: 10
    }
]
```

To make things nicer, I'm thinking of making it like this:

```yaml
archive: game1.zip,
unbuffered: true,
generator: {
    source: inputgen.cpp,
    flags: [-O3],
},
test_cases: [
    {
        in: game1.1.in,
        generator_argv: [0, 1, 2, 3],
        points: 10
    },
    {
        interactor: game1.py,
        points: 10
    }
]
```
