### ISSUE TITLE
Redirect sys_open calls to stdin/stdout

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#97]
Some problems state that you should "read from 'DATA0.txt'", and/or "output to 'OUTPUT.txt'". It's sketchy to edit the problem statements to read from stdin/stdout, but we can easily redirect a `open('DATA0.txt', 'r')` to return the stdin handle.

**Comment by quantum5** [comment]
It is quite easy to redirect such attempts to returning `0` but the closing will see `stdin` forever closed.

**Comment by quantum5** [comment]
I suppose we could convert `open` into `dup` calls, but this is slightly overcomplicating things.

**Comment by Xyene** [comment]
I don't expect any submission will attempt to read a file and then read from `stdin`, so it should be fine.

**Comment by quantum5** [comment]
The problem is closing the wrong fd. Closing stdin in runtime shutdown would result in horrors, especially considering fd can be reused.

**Comment by Xyene** [comment]
This appears to work at the most basic level.

`init.yml`:

```yaml
io_redirects:
  DATA.out:
    fd: stdout
    mode: w

archive: helloworld.zip
output_prefix_length: 1024
test_cases:
- {in: helloworld.in, out: helloworld.out, points: 100}
```

Example session:
```python
dmoj> submit helloworld PY2
import sys
with open('DATA.out', 'w') as f:
    print>> f, "Hello, World!"
:q
Start grading helloworld/1 in PY2...
Test case  1 AC [0.043s | 3192kb]
Done grading helloworld/1.
```
